/**
 * RECEPTURY per rodzaj zadania: co agent MUSI opisać (pole `karta`), jak zbudować prompt (szkielet), czego nie pisać.
 * Instrukcja kroku 2 = część wspólna (agent-instrukcja.ts) + JEDNA receptura wybrana w kroku 1. Żadnych konkretnych rzeczy ze zdjęć.
 */
export type RodzajZadania = 'zamiana_osoby' | 'zamiana_twarzy' | 'zamiana_obiektu' | 'wstawienie' | 'przeniesienie' | 'usuniecie' | 'zmiana_tla' | 'perspektywa' | 'edycja'

export const RODZAJE_ZADAN: RodzajZadania[] = ['zamiana_osoby', 'zamiana_twarzy', 'zamiana_obiektu', 'wstawienie', 'przeniesienie', 'usuniecie', 'zmiana_tla', 'perspektywa', 'edycja']

const KARTA = 'Fill the JSON field "karta" (an object with one short English entry per REQUIRED DESCRIPTION below) BEFORE you write "prompt", then build the prompt from the card. Every entry must be concrete and specific to what you SEE; "karta" never goes to the image model by itself, only through the prompt you write.'

const OBIEKT_RAMKA = {
  opis: `- OBJECT SWAP / MOVE / INSERT: place it so it looks logical, not just near the pin. State (1) the exact spot: the pin's position described with two nearby landmarks and which surface it lies on (road, floor, shelf, grass…), and that the lowest contact points of the object touch that surface exactly at the pin; (2) ORIENTATION: which way the object faces or points, derived from the scene's own lines (direction of the road, path, wall, table edge, perspective lines) — a vehicle or piece of furniture is aligned with them, never at a random angle; (2b) REFERENCE SIDE: look at which side of the object the reference photo actually shows (front, rear, side, top). Prefer an orientation in which the base camera sees THE SAME SIDE the reference shows, as long as it is consistent with the scene's lines and the user did not ask otherwise — the less the model has to invent from imagination (an unseen rear, an unseen side), the more it stays the same exact item. If the orientation requires an unseen side, say that the unseen side must follow the same design language, model generation, proportions, lights, trim and colour as the visible side; and always name the identifying details visible in the reference (grille, lights, wheels, badge, plate area, trim, colour). (3) VIEWPOINT: describe the base camera (height, angle, e.g. high aerial, eye level, looking down) and say the object is shown exactly from that viewpoint — its reference may be shot from another height or angle, so it must be re-rendered from the base camera's viewpoint, with the correct foreshortening and visible sides; (4) that it appears exactly once; (5) what is removed (if anything); (6) the SIZE (see STEP 5); (7) contact shadow and cast shadow consistent with the scene light. Never let the reference photo decide the size, viewpoint or position.`,
}

export const RECEPTURY: Record<RodzajZadania, string> = {
  zamiana_osoby: `TASK RECIPE — PERSON SWAP (a person in [BASE] is replaced by a person from a reference).
${KARTA}
REQUIRED DESCRIPTIONS ("karta"): replaced_person (look and clothes as seen in [BASE]); base_pose (crop — how much of the body is in frame and how large the head is, camera angle and distance, head tilt, gaze, expression, what each arm and hand does, what is held, posture, position and size in frame); head_size_relative (the replaced head relative to the shoulders and to other heads in [BASE]); new_person_face (face shape and jaw, eyes, eyebrows, nose, mouth and lips, facial hair or none, skin tone and marks, age); new_person_hair (exact colour, length, texture, parting, fringe, back and sides, overall cut); new_person_build; new_person_worn (every worn item: clothes, glasses, earphones, hat, jewellery, watch, belt); face_visibility (which features are hidden or small in the reference); keep_from_base.
PROMPT SKELETON (in this order): 1 opening; 2 who is replaced; 3 who the new person is (the identity features from the card, feature by feature); 4 pose / framing / expression from the base; 5 what of the replaced person must not survive; 6 what stays in the scene.
- PERSON SWAP, MANDATORY OPENING: start with "The result is [BASE] itself — the same photograph, same background (name 2–3 concrete background elements of [BASE]), same camera and framing — with only the person changed. Never output [REF1] or its background." Do NOT say the person is "transferred" or "copied" as a whole: say the person in [BASE] is REPLACED by a person who looks like the one in the reference, standing/posed exactly as the original and photographed in [BASE]'s scene. Objects the reference person merely HOLDS in their hands are left out unless the user asked for them; whatever the original person holds stays. Things the reference person WEARS on the body or face (glasses, sunglasses, earphones, hat, jewellery, watch, belt, scarf) are part of the new person's look and DO come along — never write that they must not be transferred; a gesture (peace sign, hand on chin) is a pose and does not come along.
- PERSON SWAP: describe the replaced person (as the user sees them: look, clothes) and the new person (look, clothes) so they cannot be confused. ALL appearance of the new person comes from the reference: face and every facial feature, hair, skin, build, clothing, accessories — name what you can see. IDENTITY DESCRIPTION IS MANDATORY and must be specific, feature by feature: face shape and jaw, eyes (shape, colour), eyebrows (thickness, shape), nose, mouth and lips, facial hair (moustache, stubble, beard — say if there is none), skin tone and marks, HAIR (exact colour, length, texture — straight / wavy / curly, parting, fringe, back and sides, overall fryzura), age, build, then every worn item. Do not paraphrase the hair loosely ("light brown hair" is not enough: say how it is cut and how it falls) and never omit glasses or facial hair that are visible. NOTHING of the appearance of the replaced person may survive. POSE AND FRAMING FROM THE BASE, NEVER FROM THE REFERENCE: first describe concretely, from [BASE], how the replaced person appears — crop (how much of the body is in frame, how large the head is), camera angle and distance, head tilt and gaze direction, expression, both arms and hands (what each does), everything they hold or lean on, their posture. The prompt must state all of that as the pose of the new person. The reference only supplies appearance: ignore its pose, crop, camera distance, expression and background, even if it is a full-body shot and the base is a close-up (or the reverse) — the new person is re-posed and re-framed to match the base exactly. Whatever the replaced person holds or wears as a prop of the scene (items in hands) stays as in the base unless the request says otherwise; what the reference person holds does not come along. HEAD AND BODY PROPORTIONS: the new head must be exactly as large in the frame as the replaced person's head (state the replaced head's size relative to their shoulders and to the other heads in [BASE]) — a reference that is a tight close-up or a thumbnail has a huge face on a small canvas, so never scale the head to the reference. The new person keeps the replaced person's overall build scale, shoulder width and head-to-body ratio as seen in [BASE]; if there are other people in [BASE], state that the new head is the same size as theirs at that distance. The only things kept from the base person are the pose, body direction, position, size and facial expression (mimic). Keep the scene, light and all text of the base. If the reference face is small or partly hidden, say which features are visible and that the hidden ones must be built consistently with them. If the request keeps something of the original, say exactly that stays.`,
  zamiana_twarzy: `TASK RECIPE — FACE SWAP (only the face of a person in [BASE] is replaced by the face of a person from a reference; body, clothes, hair of the base stay unless the user says otherwise).
${KARTA}
REQUIRED DESCRIPTIONS ("karta"): base_face_angle (head rotation, tilt, gaze, expression, lighting direction and colour on the face, what covers the face: hair strands, glasses, hands); new_face (face shape, jaw and chin, cheekbones, eyes — shape, spacing, colour, eyebrows, nose, mouth and lips, facial hair or none, skin tone, marks and moles, age cues); kept (hairstyle, clothes, body, background — unchanged unless asked); small_or_distant (is the base face small / far? then say the face must be rebuilt consistently at that small scale, the same identity).
PROMPT SKELETON: 1 the result is [BASE] with only the face changed; 2 whose face is replaced; 3 the new face feature by feature; 4 match the base's angle, expression intensity, light and grain; 5 blend forehead, temples, jaw, ears, neck and hairline without any seam; 6 everything else unchanged.
DO NOT: change body, clothes, pose, hairstyle, background or framing; copy the reference expression, lighting or background.`,
  zamiana_obiektu: `TASK RECIPE — OBJECT SWAP (an object in [BASE] is replaced by an object from a reference).
${KARTA}
REQUIRED DESCRIPTIONS ("karta"): old_object (kind, colour, where exactly it is — surface and two landmarks — and how it is oriented); old_object_size (how much of the frame it fills: its tight box as fractions of the frame width and height, and its visual mass — is it huge, bulky, thin; how it compares with the horizon, the ground and the other things around it); old_object_rendering (HOW the replaced object is rendered: opacity / transparency — solid, semi-transparent, ghostly, see-through to the background; blur or softness; glow, haze, tint, outline, reflections; how the light passes through or falls on it — with the degree, e.g. "about 60% opaque, the grass shows through"); new_object (kind, shape, colour, material, distinctive details, markings and text, proportions, which side the reference shows); orientation_in_scene (facing, angle relative to the camera and the scene's lines); camera (height / angle of the base camera); moving_parts (hinges, doors, handles, cables — open or closed state); completeness (the object is whole, not cut off, unless the frame crops it); leftovers (shadow, reflection, exposed background to rebuild).
PROMPT SKELETON: 1 the result is [BASE]; 2 which object disappears (description + spot with landmarks and x/y); 3 which object enters (description from the card; the reference side shown); 4 SAME SIZE AND MASS (below); 5 SAME RENDERING (below); 6 orientation, viewpoint of the base camera and foreshortening; 7 contact shadow, cast shadow, light; 8 what stays unchanged.
- OBJECT SWAP KEEPS THE REPLACED OBJECT'S PRESENCE: the new object takes over the exact footprint of the old one — the same region of the frame, the same visible width and height, the same apparent volume, bulk and mass, standing in the same place with the same contact with the ground. The size comes from the REPLACED object as it looks in [BASE], NOT from the real-world size of the new thing and NOT from the reference photo: if the old object is huge, the new one is just as huge (an oversized, exaggerated or surreal scale is kept as it is); if it is small, the new one is small. Say it in the prompt in plain words with the box fractions from the card ("it fills the same area: about N% of the frame width and M% of its height, the same bulk"). Only change this when the user explicitly asks for another size ("smaller", "life-size", "twice as big"). Do NOT fill "skala" for an object swap (leave it null).
- OBJECT SWAP KEEPS THE REPLACED OBJECT'S RENDERING: the new object inherits how the old one is shown — its transparency / opacity (a semi-transparent or ghostly object stays semi-transparent to the same degree, the background showing through the new object just as it did through the old one), blur or softness, glow, haze, tint and edge quality. State the degree explicitly in the prompt ("rendered semi-transparent, about N% opaque, the hillside visible through it") and that the new object must NOT become fully solid, opaque or sharper than the old one. Identity (shape, markings, colour pattern, details) comes from the reference; the way it is rendered in the scene comes from the replaced object.
${OBIEKT_RAMKA.opis.replace(/\(6\) the SIZE \(see STEP 5\);/, '(6) the SIZE — for an object swap exactly the size of the replaced object (see OBJECT SWAP KEEPS THE REPLACED OBJECT\'S PRESENCE);')}`,
  wstawienie: `TASK RECIPE — INSERT (something from a reference is added to [BASE]; nothing disappears).
${KARTA}
REQUIRED DESCRIPTIONS ("karta"): new_object (kind, shape, colour, material, distinctive details, markings, proportions, which side the reference shows); spot (surface it lies on, two nearby landmarks, x/y fractions of [BASE]); orientation_in_scene (derived from the scene's own lines — road, wall, table edge); camera (height / angle of the base camera); size (anchors with real sizes and the real dimensions of the thing — STEP 5); moving_parts; completeness; edge_of_frame (is the spot at the frame edge — then the frame may crop it).
PROMPT SKELETON: 1 the result is [BASE] with one thing added; 2 what is added (from the card); 3 where (surface, landmarks, x/y), contact points on the surface; 4 orientation and the base camera's viewpoint; 5 size relative to the surroundings; 6 shadows and light; 7 appears exactly once; nothing else from the reference.
${OBIEKT_RAMKA.opis}`,
  przeniesienie: `TASK RECIPE — MOVE (a thing in [BASE] is moved to another spot in the same photo; or a thing from a reference is brought to a spot — then follow the INSERT logic and also erase nothing).
${KARTA}
REQUIRED DESCRIPTIONS ("karta"): object (exhaustive description of THIS exact one — kind, colour, material, shape, size, orientation — and how it differs from similar ones nearby); spot_a (what is there, landmarks, x/y); spot_b (surface, two landmarks, x/y); size_at_b (only perspective changes the apparent size — anchors at B's depth); orientation_at_b (from the lines of spot B); background_a (what is rebuilt at A); edge_of_frame.
- MOVE INSIDE ONE PHOTO (task "przeniesienie", everything is in [BASE], no reference image — typically two pins on the same photo): the key verb is MOVE, never copy / add / duplicate. Write it as: "MOVE the <concrete description of this exact object> from <spot A> to <spot B> — it is moved, not copied: exactly one instance exists in the result and spot A is left empty with the background rebuilt (surface, grass, shadows)." Describe the object in detail from the photo itself (type, colour, material, shape, size, current orientation) so the model grabs the right one; describe spot A (what is there + landmarks + x/y of [BASE]) and spot B (surface, two landmarks, x/y). The object keeps its identity, appearance and real size — only the apparent size changes with perspective and distance (see STEP 5), and its orientation follows the lines of spot B. Order inside the prompt: (1) ERASE — spot A must end up empty, rebuilt with the surrounding surface and background, done first and stated as a hard requirement; (2) PLACE at spot B; (3) end with a check sentence: "FINAL CHECK: the <object> appears exactly once, at spot B; spot A shows only background." Also fill "ruch" with the pin numbers: the pin on the thing that moves ("z_pinezki") and the pin of the destination ("do_pinezki"), and "cel" with the tight box of the thing at spot A. Do not ask for a reference and do not call anything [REF1].`,
  usuniecie: `TASK RECIPE — REMOVE.
${KARTA}
REQUIRED DESCRIPTIONS ("karta"): target (exactly what disappears — description, spot with landmarks and x/y, all instances if several); behind (what lies behind and under it: surface, texture, pattern, lines to continue); leftovers (shadow, reflection, contact marks, cast light); neighbours (adjacent things that must stay untouched).
PROMPT SKELETON: 1 the result is [BASE]; 2 remove the target completely (description + spot); 3 rebuild what lies behind, continuing lines, patterns and textures; 4 no traces: shadow, reflection, marks, halo; 5 everything else unchanged.
- REMOVE: what disappears with its shadow and reflection, and that the background is rebuilt.`,
  zmiana_tla: `TASK RECIPE — BACKGROUND / SCENERY CHANGE.
${KARTA}
REQUIRED DESCRIPTIONS ("karta"): foreground_keep (people / objects that must stay, their edges, hair and semi-transparent parts); new_background (kind of place, depth, main elements, time of day, weather); light_match (direction, colour and softness of the new light that must fall on the foreground); perspective_match (camera height and angle; horizon); contact (where the foreground touches the ground and its shadow).
PROMPT SKELETON: 1 keep the foreground exactly (description); 2 the new background; 3 relight and match perspective and sharpness so it is one photograph; 4 no cut-out look, no halo.`,
  perspektywa: `TASK RECIPE — NEW CAMERA ANGLE.
${KARTA}
REQUIRED DESCRIPTIONS ("karta"): current_view (height, angle, distance); new_view (in words: how the camera moves and what direction); constants (place, objects, people, light, time of day); newly_visible (parts that become visible and must be invented consistently).
PROMPT SKELETON: 1 same place and moment, new camera position; 2 the new view precisely; 3 what stays identical; 4 how newly visible parts must look (consistent with what is known).`,
  edycja: `TASK RECIPE — FREE EDIT / STYLE.
${KARTA}
REQUIRED DESCRIPTIONS ("karta"): changes (a list of exactly what changes); keep (what must stay identical); intensity (subtle / strong); style_source (if a reference gives a style: take only the style, not its content).
PROMPT SKELETON: 1 the result is [BASE]; 2 each change, concretely; 3 what stays; 4 no unrequested changes.`,
}

export function instrukcjaAgenta(wspolna: string, zadanie?: string): string {
  const r = RECEPTURY[zadanie as RodzajZadania]
  const reszta = r ?? RODZAJE_ZADAN.map(k => RECEPTURY[k]).join('\n\n')
  return `${wspolna}\n\n${reszta}`
}
