// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwuvszxeutvmzcfuetuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dXZzenhldXR2bXpjZnVldHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MzEwOTMsImV4cCI6MjA2NjIwNzA5M30.1kTSozBT2TCeA0SMc-fr_H-TnNA0x8--Gk-OBH444uY";

// Always use localStorage for session persistence.
// "Remember me" controls whether we clear the session on browser close (via beforeunload).
// This prevents logout on hot-reload / preview refresh while keeping session-only behavior
// when the user hasn't checked "Remember me".
const customStorage = {
  getItem: (key: string): string | null => {
    // Migration: check sessionStorage for legacy sessions and move them
    const fromSession = sessionStorage.getItem(key);
    if (fromSession) {
      localStorage.setItem(key, fromSession);
      sessionStorage.removeItem(key);
    }
    return localStorage.getItem(key);
  },
  setItem: (key: string, value: string): void => {
    localStorage.setItem(key, value);
    sessionStorage.removeItem(key); // cleanup legacy
  },
  removeItem: (key: string): void => {
    localStorage.removeItem(key);
    sessionStorage.removeItem(key);
  },
};

// Device Trust system handles session persistence (30-day tokens).
// The old beforeunload token-clearing logic has been removed — sessions
// now expire naturally via Supabase JWT expiry, and device trust tokens
// allow seamless re-login.

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/*
  ════════════════════════════════════════════════════════════════════════
   FUNKCJE EDGE PRZEZ PROXY — TYLKO W TRYBIE DEWELOPERSKIM
  ════════════════════════════════════════════════════════════════════════
  Bez tego logowanie na `localhost:8080` jest niemożliwe: funkcje mają listę
  dozwolonych origin (`_shared/cors.ts`), na której localhost się nie znajduje.
  Przeglądarka blokuje żądanie, a supabase-js pokazuje mylące „Failed to send
  a request to the Edge Function" — brzmiące jak awaria funkcji, choć funkcja
  odpowiada normalnie. Powód i decyzja: `vite.config.ts`.

  DLACZEGO PODMIANA `fetch`, A NIE OPCJA `functions: { url }`:
  ta wersja supabase-js opcji NIE CZYTA — wylicza adres funkcji z adresu
  bazowego (`new URL("functions/v1", supabaseUrl)`). Opcja przechodzi przez
  TypeScript i jest po cichu ignorowana, więc wyglądałoby to na działające.
  Sprawdzone w źródle biblioteki, nie założone.

  Świadomie NIE dopisujemy localhost do listy dozwolonych origin na produkcji
  — to poluzowanie bezpieczeństwa dla wygody dewelopera.
*/
/**
 * Baza adresowa funkcji edge dla RĘCZNYCH `fetch` (poza supabase-js).
 * W dev celuje w proxy Vite (`/nb-funkcje`, patrz vite.config.ts) — inaczej
 * każdy własnoręczny fetch omija `fetchZProxy` niżej i ginie na CORS
 * z mylącym `Failed to fetch (model: …)`. Zmierzone 11.08.2026: czternaście
 * miejsc w src/ budowało pełny adres samodzielnie i ŻADNE nie działało
 * z localhost:8080, choć invoke przez klienta działał.
 * UWAGA: adresy POKAZYWANE użytkownikowi (MCP_SERVER_URL) muszą zostać
 * absolutne — to nie są nasze fetche.
 */
export const FUNKCJE_BAZA_URL = import.meta.env.DEV
  ? '/nb-funkcje'
  : `${SUPABASE_URL}/functions/v1`;

const fetchZProxy: typeof fetch = (wejscie, init) => {
  const adres = typeof wejscie === 'string' ? wejscie : wejscie instanceof URL ? wejscie.href : wejscie.url;
  const prefiks = `${SUPABASE_URL}/functions/v1`;
  if (adres.startsWith(prefiks)) {
    const przez = `${window.location.origin}/nb-funkcje${adres.slice(prefiks.length)}`;
    // Request trzeba odtworzyć, bo jego `url` jest tylko do odczytu.
    return fetch(wejscie instanceof Request ? new Request(przez, wejscie) : przez, init);
  }
  return fetch(wejscie, init);
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  ...(import.meta.env.DEV ? { global: { fetch: fetchZProxy } } : {}),
  auth: {
    storage: customStorage,
    storageKey: 'sb-iwuvszxeutvmzcfuetuo-auth-token',
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    // Disable navigator.locks to prevent "Lock broken by another request with the steal option"
    // errors that cause random logouts, especially on mobile/PWA and multi-tab scenarios
    lock: async (_name: string, _acquireTimeout: number, fn: () => Promise<any>) => {
      return await fn();
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});
